### PR TITLE
Update deps & general cleanup!

### PR DESCRIPTION
**Pull request by RedstoneWizard08**
Hi! Firstly, this project is insanely cool, so I wanted to just clean up the code a little and update the dependencies. I've tested it and everything works as it did before. As I have seen from the files present this seems to be some sort of academic research project, so I didn't want to interfere much, as that could cause issues for you, so I just decided to do a little cleanup without changing any real functionality. You may notice that debug messages are gone, and that's because it uses the `tracing` crate now, and to see them you can just run it with the environment variable `RUST_LOG=debug`. I hope you like it! :)

### CODE REVIEW

**Comment by 4321ba** [comment]
Hello, wow thats a lot of modifications! First of all, thank you very much for your interest and time :DD! I'll get back to this project in the coming weeks, this will be my thesis for BSc (bachelor's) :DD. For this semester one of my goals is to clean up the code and make it more understandable, as well as easier to use (configuring it with commandline arguments), and make it work for a wider range of songs (next to writing like 40 pages about it xd). While I'm not sure It'll be easier for me to continue from your modifications compared to my admittedly pretty messy one I left from last semester, I'll look at your modifications closely, and will probably continue from that (the tracing crate sounds pretty useful e.g. :D).

**Comment by 4321ba** [comment]
Hii, thank you again and sorry for the long delay! I was thinking a lot about merging it, but the biggest problem is personal preference, I feel like I can read concise/compact code better, so I don't really like that the autoformatter splits 1 semi-long line into 5-6 lines. However if multiple people are working on code then ofc it has a lot of benefits. But mostly I will be working on this and I feel like it's better if I leave it like it was, at least in this regard. But thank you very much and I'll be using parts of the code to improve the project :DDD, e.g. I'll start by updating the dependencies

**Comment by RedstoneWizard08** [comment]
No problem! Good luck!

**Comment by 4321ba** [comment]
Hello, thanks again! I did a bigger cleanup today and also used your modifications for e.g. the tracing logger :D

now the code is much slower, but much more precise (at least when used with songs exported with nbswave), sadly we lost some generality, but this will mostly be my final version for some time. Now it uses the derivative for the minimum search as well.

if you'd like to touch the code / modify it further, let me know, I'd be glad to help! I can't promise anything as I'm not that active on GitHub, but It'd be awesome seeing the project continue!

**Comment by RedstoneWizard08** [comment]
Yeah! This project is awesome and super cool and I'll probably parallelize some of it with [rayon](https://docs.rs/rayon) to make it faster.

**Comment by 4321ba** [comment]
Nicee :DD! I also tried doing that and it worked great (there is still a comment in main.rs), however now it's using the previously recognized note's decay to make the next recognition better, so in this regard we lost the ability to run them in parellel - at least as a straightforward modification, but ofc I'm sure there could be some way :D, e.g. by splitting the music into 4 equal parts and starting recognition from 4 points moving forward - or by replacing the previously recognized note's decay with something else.

**Comment by RedstoneWizard08** [comment]
> but ofc I'm sure there could be some way

lmao I have no idea how this app works I just know rust xD
I'd have to do some research (and probably translate your documentation into english lol)

**Pull request closed without merging**
